//v26 © 2011 Tynt

Tynt=window.Tynt||[];
if(typeof Tynt.TIL=="undefined"){(function(){var Ja=function(){var i=document,m=i.body,p=i.documentElement,$=eval("/*@cc_on!@*/false"),aa=function(a,b){for(var c="",f=0;f<b;f++)c+=a;return c},v=aa("a",50),s=(Tynt.e||"")+"ic.tynt.com",oa=(Tynt.e||"")+"de.tynt.com/deb/?id="+v,w=function(){return(new Date).getTime()},t=function(a){return a.replace(/^\s+|\s+$/g,"")},M=function(a,b){for(var c in a)if(a.hasOwnProperty(c))b[c]=a[c]},C=function(a,b,c){a=i.createElement(a);M(b,a);M(c,a.style);return a},q,
N;if(window.addEventListener){q=function(a,b,c){a.addEventListener(b,c,false)};N=function(a,b,c){a.removeEventListener(b,c,false)}}else{q=function(a,b,c){a.attachEvent("on"+b,c)};N=function(a,b,c){a.detachEvent("on"+b,c)}}var O=function(a,b){var c=location.hostname.split("."),f=2;do{var d=c.slice(c.length-f,c.length).join(".");i.cookie=a+";path=/;domain=."+d+";"+b;f++}while(i.cookie.indexOf(a)==-1&&f<=c.length);if(i.cookie.indexOf(a)==-1)i.cookie=a+";path=/;"+b},ba=function(a){i.readyState=="complete"?
a():q(window,"load",function(){setTimeout(function(){if(typeof i.readyState=="undefined"&&!$)i.readyState="complete";a()},10)})},n=function(a,b){var c=[],f=function(d,e){var h="http://"+d.replace("id="+v,"id="+Tynt.join("~"));if(h.indexOf(s+"/b/p?")>-1&&typeof Tynt.b=="string")h+="&b="+Tynt.b;var k=new Image(1,1);if(e)k.onerror=e;k.src=h};n=function(d,e){c.push([d,e])};ba(function(){n=f;for(var d=0;d<c.length;d++)n(c[d][0],c[d][1]);c=null});n(a,b)},ca=function(a){var b=[],c="",f;for(f in a)if(a.hasOwnProperty(f)){b.push(c,
f,"=",a[f]);c="&"}return b.join("")},P=function(a){for(var b=0,c=a.length<100?a.length:100,f=0;f<c;f++)b+=a.charCodeAt(f);a=Math.floor(Math.random()*3844);c=Math.abs(w()-12281184E5);return da(c,7)+da((b+a)%3844,2)},ea=function(a){if(a<62)return"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(this);else{var b=Math.floor(a/62);a=a-b*62;return b>=62?ea(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a):"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(b)+
"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a)}},da=function(a,b){var c=ea(a);return aa("0",b-c.length)+c},fa=function(a){return(a=t(a))?a.split(/\s+/i).length:0},Q=t((i.title||location.hostname).toString()).replace(RegExp(location.hash,"g"),""),ga=function(){for(var a=i.getElementsByTagName("link"),b=0;b<a.length;b++)if(a[b].getAttribute("rel")&&a[b].getAttribute("rel").match("canonical")&&a[b].getAttribute("href")){a=a[b].getAttribute("href");b=location.protocol+"//"+
location.host+location.pathname;var c=i.getElementsByTagName("base")[0];if(c)if(c=c.getAttribute("href"))b=c;if(!a.match(/^http/)){if(a.charAt(0)=="/"){c=b.indexOf("/",9);if(c>-1)b=b.slice(0,c)}else{c=b.lastIndexOf("/");if(c>9)b=b.slice(0,c+1);else b+="/"}a=b+a}return a}return""},E=function(a){return a.replace(/^https?:\/\//,"")},F=function(a,b){for(var c=b+"=",f=a.split(";"),d=0;d<f.length;d++){for(var e=f[d];e.charAt(0)==" ";)e=e.substring(1,e.length);if(e.indexOf(c)==0)return e.substring(c.length,
e.length)}return null},pa=function(){var a=F(i.cookie,"tracertraffic"),b=encodeURIComponent(E(ga())),c=i.location.hash;c=/tynt=/.test(c)?c.match(/tynt=?([^?&$#]*)/)[1]:false;var f=s+"/b/p?id="+v+(a?"&et="+a:"")+(c?"&a="+c:"")+"&ts="+w(),d=f+(b?"&cu="+b:""),e=d+(i.referrer?"&r="+encodeURIComponent(E(i.referrer)):"");a=e+"&t="+encodeURIComponent(Q);n(a,function(){n(e,function(){n(d,function(){n(f)})})})},R=function(){var a=[];return function(b){for(var c=a.length-1;c>=0;c--)if(a[c]==b)return false;
a.unshift(b);a.length>3&&a.pop();return true}},qa=R(),ra=R(),sa=function(){var a,b=function(){window.removeEventListener("blur",b,false);S(a);return true};return function(c){a=c.target||c.srcElement;window.removeEventListener("blur",b,false);if(a.nodeName=="IMG"&&a.parentNode.nodeName!="A"){window.addEventListener("blur",b,false);setTimeout(function(){i.removeEventListener("blur",b,false)},1E4)}return true}}(),ha=function(a){S(a.target||a.srcElement,true)},G,ia=function(a){a=a.target||a.srcElement;
G=a.nodeName=="IMG"?a:null},T=function(){var a=function(h){return typeof h.pageX=="number"?{x:h.pageX-(p.scrollLeft?p.scrollLeft:m.scrollLeft),y:h.pageY-(p.scrollTop?p.scrollTop:m.scrollTop)}:{x:h.clientX,y:h.clientY}},b=function(h){h=a(h);return h.x<=0||h.y<=0||h.x>=m.clientWidth||h.y>=m.clientHeight},c=function(h){h=a(h);return h.x<=0||h.y<=0||h.x>=p.clientWidth||h.y>=p.clientHeight},f=function(h){return h.target.nodeName=="#document"},d=function(h){h=a(h);return h.x<=4||h.y<=4||h.x>=p.clientWidth-
4||h.y>=p.clientHeight-4},e=function(h){e=navigator.userAgent.match("MSIE")?!i.compatMode||i.compatMode.indexOf("CSS")==-1?b:c:navigator.userAgent.match("Firefox")?f:d;e(h)};return function(h){if(G&&e(h)){S(G);G=null}return true}}(),ta=function(){function a(j,l){if(o(j))n(s+"/b/o?id="+v+(l?"&i=":"&l=")+encodeURIComponent(j)+"&ts="+w())}function b(j){var l=j.target||j.srcElement;if(j.button<2)for(;l&&l!=i;){j=l.href;if(l.nodeName=="A"&&j&&location.href.split("#")[0]!=j.split("#")[0]&&!/^javascript/i.test(j)){a(j);
break}l=l.parentNode}}function c(){k&&a(k,true)}function f(j){if(j){j=j.target||j.srcElement;k=j.src||j.data||"flash";q(window,"blur",c)}}function d(){k=null;N(window,"blur",c)}function e(j){q(j,"mouseover",f);q(j,"mouseout",d)}function h(){k&&a(k,true)}var k,o=R();q(document,"mousedown",b);ba(function(){for(var j=i.getElementsByTagName("iframe"),l=j.length-1;l>=0;l--){var r=j[l];if(r.src)e(r);else if(r.name)try{q(frames[r.name].document,"mousedown",b)}catch(u){}}j=i.getElementsByTagName("object");
for(l=j.length-1;l>=0;l--)e(j[l])});q(window,"beforeunload",h);q(window,"unload",h)},x;if(Tynt.c)x=function(){};else{Tynt.c=true;x=function(){var a=true,b,c=function(f,d){var e={id:v,wc:fa(d),c:d,f:a?1:0,t:Q};M(f,e);a=false;var h=e.trace_type;delete e.trace_type;var k=e.g;delete e.g;for(var o=[],j=["id","wc","f","w","h","t","c"],l=0;l<j.length;l++){var r=j[l],u=e[r];u&&o.push([r,encodeURIComponent(u).replace(/\'/g,"%27")]);delete e[r]}for(var y in e)if(e.hasOwnProperty(y))(j=e[y])&&o.push([y,encodeURIComponent(j).replace(/\'/g,
"%27")]);e=[];l=2048-(("http://"+s+"/a/t/x#?").length+(3+k.length)+5);r=o.length;var B=u=0,z=0,U,H,V,I,J=0;for(e[J]={g:k,tp:null};u<r&&e.length<35;){U=o[u][0];y=o[u][1];V=U.length+2;H=l-V-B;if(H>0){j=y.substring(z,z+H);I=j.slice(-2).indexOf("%");if(I>-1){j=y.substring(z,z+H-2+I);B+=I+2}B+=j.length+V;z+=j.length;e[J][U]=j}else B=l;if(B>=l){e[++J]={g:k,p:J};B=0}if(z>=y.length){u++;z=0}}e[0].tp=e.length;n(s+"/b/t/"+h+"?"+ca(e[0]));for(k=1;k<e.length;k++)n(s+"/b/x/"+h+"?"+ca(e[k]))};/tynt=nout/.test(location.href)||
ta();if(window.addEventListener){navigator.userAgent.match("Firefox/2")||m.addEventListener("copy",ha,false);window.addEventListener("mousedown",ia,false);window.addEventListener("dragleave",T,false);window.addEventListener("dragexit",T,false);i.addEventListener("contextmenu",sa,false)}else{m.attachEvent("oncopy",ha);i.getElementsByTagName("html")[0].attachEvent("ondragleave",T);m.attachEvent("onmousedown",ia)}if(i.cookie.indexOf("tracertraffic=")!=-1)if(!i.referrer||i.referrer.indexOf(location.host)==
-1)O("tracertraffic=0","expires=Thu, 01 Jan 1970 00:00:00 GMT");pa();n(oa);return function(f,d){if(!i.getElementById("tyntSS")){var e;if(d)e=typeof getSelection!="undefined"?getSelection().toString():i.selection.createRange().text;var h=f.src;h&&!e&&ra(h)&&c({g:P(h),trace_type:3,w:f.width,h:f.height},h);if(e&&t(e).length&&f.nodeName!="TEXTAREA"&&f.nodeName!="INPUT"){h=qa(e);var k={trace_type:1};if(h)b=P(e);k.g=b;var o=Tynt.m?Tynt.m(k,e):true;h&&o&&c(k,e)}}}}}var K=function(a){a=a.charCodeAt(0);return 3584<=
a&&a<=3711||11904<=a&&a<=12591||12688<=a&&a<=40959||63744<=a&&a<=64255||65072<=a&&a<=65103||131072<=a&&a<=173791||194560<=a&&a<=195103},ja=function(a){a=a.getElementsByTagName("script");for(var b=a.length-1;b>=0;b--){var c=a[b];c.parentNode.removeChild(c)}},g,ua=(Tynt.e||"")+"id.tynt.com",va={t:3,p:6,w:7},A,W,X,wa=["","Attribution","Attribution Share Alike","Attribution No Derivatives","Attribution Non-Commercial","Attribution Non-Commercial Share Alike","Attribution Non-Commercial No Derivatives"],
xa=["","http://creativecommons.org/licenses/by/3.0","http://creativecommons.org/licenses/by-sa/3.0","http://creativecommons.org/licenses/by-nd/3.0","http://creativecommons.org/licenses/by-nc/3.0","http://creativecommons.org/licenses/by-nc-sa/3.0","http://creativecommons.org/licenses/by-nc-nd/3.0"],ka=function(a){a=a.match(/ixzz=?([^?$#]*)/);if(!a)return null;a=a[1].match(/&([^?$]*)/);if(Tynt.k)return Tynt.k.charAt(1);if(!a||!a[1])return null;return a[1]},Y=function(a){return(a=a.match(/axzz([^?$]*)/))&&
a.length==2?a[1]:null},ya=function(a){var b=ga();b=b&&g.c!==false?b:location.href;b=b.replace(/#(i|a)xzz=?(.*)$/g,"");return b+"#"+("ixzz"+a)},la=function(a){var b=new Date(w()+864E5);O("tracertraffic="+a.toString(),"expires="+b.toUTCString())},za=function(){var a=location.href.match(/ixzz=?([^?&$#]*)/);if(a=(a&&a.length==2?a[1]:null)||Tynt.h){var b=ka(location.href);a=s+"/b/v?g="+a+(/\?trace_owner_view/.test(location.href)?"&o=y":"")+"&id="+v+(b?"&s="+b:"")+"&r="+encodeURIComponent(E(i.referrer))+
"&ts="+w();n(a);return true}return false},Aa=function(a){n(s+"/b/a?g="+a+"&id="+v+"&r="+encodeURIComponent(E(i.referrer))+"&ts="+w(),function(){})},ma=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},D=false,Ba=function(a){if(D)return false;D=true;var b="";if(g.a){var c=ya(a),f='<a style="color: #003399;" href="';b+=g.ap;if(g.st)b=b+f+c+'">'+ma(Q)+"</a> ";if(g.su)b=b+f+c+'">'+ma(c)+"</a>";if(g.as.length>0)b=b+"\n<br>"+g.as+" ";if(g.cc>0)b=b+"\n<br>Under Creative Commons License: "+
f+xa[g.cc]+'">'+wa[g.cc]+"</a>"}if(g.el){if(b.length>0)b+="\n<br>";b+=g.el}if(A){if(b.length>0)b+="\n<br>";b=X?b+W+f+"http://tcr"+g.s+".tynt.com/ads/"+X+"/"+a+'">'+A+"</a>":b+W+f+"http://tcr"+g.s+".tynt.com/ads/"+A+"/"+Z+"/"+a+'">'+A+"</a>"}var d,e;d=C("div",{},{overflow:"hidden",color:"#000000",backgroundColor:"#FFFFFF",textAlign:"left",textDecoration:"none",border:"none"});if(!i.selection||!i.selection.createRange){a=getSelection();if(a.toString())if(typeof a.setBaseAndExtent!="undefined"){var h=
a.getRangeAt(0);b=C("span",{innerHTML:b});if(g.t){b.innerHTML+="<br/><br/>";d.appendChild(b);d.appendChild(h.cloneContents())}else{d.appendChild(h.cloneContents());b.innerHTML="<br/><br/>"+b.innerHTML;d.appendChild(b)}ja(d);d.style.width=0.1;d.style.height=0.1;d.style.position="absolute";d.style.top="-1000px";d.style.left="-1001px";d.appendChild(i.createElement("br"));b=d.innerText.length;m.insertBefore(d,m.firstChild);if(d.innerText.length!=b)d.style.overflow="";a.selectAllChildren(d);setTimeout(function(){d.parentNode.removeChild(d);
getSelection().setBaseAndExtent(h.startContainer,h.startOffset,h.endContainer,h.endOffset);D=false},0)}else{e=C("div",{},{height:0,position:"absolute",top:"-1000px"});e.innerHTML="<br>";if(g.t){m.insertBefore(e,m.firstChild);d.innerHTML=b+"<br><br>"}else{m.appendChild(e);d.innerHTML="<br>"+b+"<br>"}e.appendChild(d);b=i.createRange();b.selectNode(d);a.addRange(b);window.setTimeout(function(){e.parentNode.removeChild(e);D=false},0)}}else{var k=p.scrollLeft||m.scrollLeft,o=p.scrollTop||m.scrollTop;e=
C("div",{},{overflow:"hidden",position:"absolute",left:k+20+"px",top:o+20+"px",width:"1px",height:"1px"});m.insertBefore(e,m.firstChild);var j=i.selection.createRange();d.innerHTML=g.t?b+"<br><br>"+j.htmlText:j.htmlText+"<br><br>"+b;ja(d);e.appendChild(i.createElement("br"));e.appendChild(d);b=m.createTextRange();b.moveToElementText(d);b.select();setTimeout(function(){m.removeChild(e);if(j.text!=""){j.select();p.scrollLeft=k;m.scrollLeft=k;p.scrollTop=o;m.scrollTop=o}D=false},0)}return true},Da=function(a,
b){var c=true;if(g.a||A||g.el){var f;f=t(b);f=f.length>=2?K(f.charAt(0))||K(f.charAt(f.length-1))||K(f.charAt(f.length/2)):K(f);var d;if(d=g.h)a:{d=(d=Ca())?d.className.split(/\s+/):[];for(var e=d.length-1;e>=0;e--)if(g.h[d[e]]!==undefined){d=g.h[d[e]];break a}d=void 0}d=d;if(d!==false&&(f&&b.replace(/\s/g,"").length>=g.aw*2||!f&&fa(b)>=g.aw)||d)if(g.a||A||g.el){c=Ba(a.g);if(g.a)a.trace_type=0}}return c},Ca=function(){return!i.selection||!i.selection.createRange?function(){var a=getSelection().getRangeAt(0),
b=a.startContainer.nodeType==3?a.startContainer.parentNode:a.startContainer;return b&&t(a.toString())==t(b.textContent)?b:null}:function(){var a=i.selection.createRange(),b=a.duplicate();b.collapse(true);return(b=b.parentElement())&&t(a.text)==t(b.innerText)?b:null}}(),Ea=function(a){var b=a?864E5:-5E3;b=new Date(w()+b);i.cookie="tracerabg="+a+";path=/;expires="+b.toUTCString()},Ga=function(a){var b;a:{b=i.getElementsByTagName("script");for(var c=0;c<b.length;c++)if(/\/show_afs_search\.js/i.test(b[c].src)){b=
true;break a}b=false}if(!b&&Fa(location)){Tynt.b=a||P(location.href);location.replace(location.href+"#axzz"+Tynt.b)}},Fa=function(a){if(a.hash!="")return false;if(typeof g.ba=="boolean"&&g.ba)g.ba=["/"];else if(!g.ba)return true;for(var b,c=g.ba.length-1;c>=0;c--){b=null;var f=g.ba[c],d=f.indexOf("/");if(d!=0){b=f.slice(0,d);f=f.slice(d)}if(!b||a.host==b)if(f.charAt(f.length-1)=="#"){if(a.pathname.indexOf(f.slice(0,-1))==0)return false}else if(a.pathname==f)return false}return true},Ha=function(a){g=
Tynt.i||window.tyntVariables||{};g.s=a.s||1;g.a=!(g.a==0||a.a==0);g.cc=g.cc||a.cc||0;if(g.cc>6)g.cc=0;g.b=!!(g.b||a.b);g.aw=Math.max(g.aw||8,8);if(g.a){g.ap=(g.ap||(typeof tyntAP!="undefined"?tyntAP:null)||"Read more:")+" ";g.as=g.as||(typeof tyntAS!="undefined"?tyntAS:null)||"";g.st=!!(g.st||a.st);g.su=!(g.su==0||a.su==0);g.sp=g.sp||a.sp;if(g.sp){X=g.spid;W=(g.spt||decodeURIComponent(a.spt||""))+" ";A=g.sp||decodeURIComponent(a.sp||"")}}},na=function(){var a=i.title.indexOf("#ixzz");if(a>-1)i.title=
i.title.substring(0,a);a=i.title.indexOf("#axzz");if(a>-1)i.title=i.title.substring(0,a)},Ia=function(){for(var a=0;a<Tynt.length;a++)if(Tynt[a]&&Tynt[a].length==22)return Tynt[a];return null},L=function(a){if(!a)return{};for(var b={},c=a.substring(a.indexOf("?")+1).split("&"),f=0;f<c.length;f++){var d=c[f].split("=");if(d[0].indexOf("amp;")==0)d[0]=d[0].substring(4);b[d[0]]=d[1]}a=a.split("/");a.pop();b.scriptPathUri=a.join("/");return b}(function(){for(var a=i.getElementsByTagName("script"),b=0;b<
a.length;b++)if(/\/tracer.*\?/i.test(a[b].src))return a[b].src;return null}()),Z=L.user||Ia();if(!Z)throw Error("Error finding Tynt Insight userId. Please check your HTML for errors.");L.user&&Tynt.push(L.user);if(!function(){var a=/tracer=test/.test(location.href);a&&n(ua+"/script/verify/"+Z);if(a)return true;if(/tracer=no_tracing/.test(location.href))return true;if(/disableTracer=/.test(location.href)){a=location.href.match(/disableTracer=([^?$]*)/)[1];var b=new Date;b.setDate(a&&a=="on"?b.getDate()+
365:b.getDate()-2);O("disableTracer=y","expires="+b.toUTCString());b=C("div",{},{zIndex:"10000",position:"absolute",top:"10%",left:"10%",width:"80%",height:"80%",backgroundColor:"white",color:"black",textAlign:"center",fontSize:"32px",paddingTop:"10%",border:"1px solid gray"});b.innerHTML="Tynt Insight has been turned "+(a&&a=="on"?"off":"on")+" in this browser.<br>You may close this window.";m.insertBefore(b,m.firstChild);return true}if(F(i.cookie,"disableTracer"))return true;return false}()){if($){na();
i.attachEvent("onpropertychange",na)}Ha(L);var S=x();x=va[ka(location.href)];if(za()){x||(x=/tynt.com/.test(i.referrer)?3:1);la(x)}Tynt.m=Da;if(g.b)if(Y=Y(location.href)){if("#axzz"+F(i.cookie,"tracerabg")!=location.hash){Aa(Y);la(2)}}else{Ga(F(i.cookie,"tracerabg"));Ea(Tynt.b)}}};Tynt.TIL=function(){document.body?Ja():setTimeout(Tynt.TIL,300)}})();Tynt.TIL()};
