%Graficos sba
%CREATEFIGURE(X1,Y1,X2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data

%  Auto-generated by MATLAB on 12-Jan-2011 11:02:56

% Create figure
close all
load dispersao

xSize = 8; ySize = 12;
xLeft = (21-xSize)/2; yTop = (30-ySize)/2;

 figure1 = figure('Color',[1 1 1]);%'PaperUnits','centimeters',...
%     'PaperPosition',[xLeft yTop xSize ySize],...
%     'Position',[1 1 xSize*50 ySize*50],...
%     ;



%  'PaperType','custom',...    
%    'PaperSize',[6 6],...
 %   'PaperPositionMode','manual',...    
 %'InvertHardcopy','off',...
  %   'Units','centimeters',...
% Create axes
axes1=axes('Parent',figure1,'YTick',[0 500 1000 1500 2000 2500 3000],...
    'XTick',[0 25 50 75 100 125 150 175 200],...
    'FontSize',12,...
    'FontName','times new roman');
% Uncomment the following line to preserve the X-limits of the axes
 xlim([0 200]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim([0 3000]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim([-1 1]);
box('on');
hold('all');

% Create plot
%plot(t,ccnc,'Marker','.','LineStyle','none');
plot(t,ccnc,'k.');
plot(tcpc,cpcMedio,'r-');
plot(tcpc,cpcMax,'g-');
plot(tcpc,cpcMin,'b-');

% Create xlabel
xlabel('Tempo (minutos)','FontSize',12,'FontName','times new roman');

% Create ylabel
ylabel('Partículas/cm^3','FontSize',12,'FontName','times new roman');
text(200,4000,'R^2=0,99','FontSize',12,'FontName','times new roman');

legend1 = legend(axes1,'show');
set(legend1,'Location','SouthEast');

stop
% Create plot
plot(X2,X2,'LineStyle',':');

% 
% set(plot1(1),'Color',[1 0 0],'DisplayName','CPC Médio');
% set(plot1(2),'Color',[0 1 0],'DisplayName','CPC Max');
% set(plot1(3),'Color',[0 0 1],'DisplayName','CPC Min');


