%Graficos sba
%CREATEFIGURE(X1,Y1,X2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data

%  Auto-generated by MATLAB on 12-Jan-2011 11:02:56

% Create figure
xSize = 8; ySize = 12;
xLeft = (21-xSize)/2; yTop = (30-ySize)/2;

 figure1 = figure('Color',[1 1 1]);%'PaperUnits','centimeters',...
%     'PaperPosition',[xLeft yTop xSize ySize],...
%     'Position',[1 1 xSize*50 ySize*50],...
%     ;



%  'PaperType','custom',...    
%    'PaperSize',[6 6],...
 %   'PaperPositionMode','manual',...    
 %'InvertHardcopy','off',...
  %   'Units','centimeters',...
% Create axes
axes('Parent',figure1,'YTick',[0 1000 2000 3000 4000 5000],...
    'XTick',[0 1000 2000 3000 4000 5000],...
    'FontSize',12,...
    'FontName','times new roman');
% Uncomment the following line to preserve the X-limits of the axes
 xlim([0 5000]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim([0 5000]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim([-1 1]);
box('on');
hold('all');

% Create plot
plot(x,y,'Marker','.','LineStyle','none');

% Create xlabel
xlabel('CPC (p/cm^3)','FontSize',12,'FontName','times new roman');

% Create ylabel
ylabel('CCNC-SDCC (p/cm^3)','FontSize',12,'FontName','times new roman');
text(200,4000,'R^2=0,99','FontSize',12,'FontName','times new roman');
a=[0 5000];
plot(a,a,'r-')
stop
% Create plot
plot(X2,X2,'LineStyle',':');


